### ISSUE TITLE
Doesn't run at all

### ISSUE THREAD

**Issue by SelaOAL** [Developer-Autodesk/client-steampunked-morgan#1]
I'm trying to run it locally on my machine (win10) but it doesn't even start.

After doing all the required steps, when I type node server.js, I get:

```
module.js:471
    throw err;
    ^

Error: Cannot find module './lib/compat'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\viewer-steampunked-morgan-master\node_modules\express\node_modules\depd\index.js:11:47)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

I found that reinstalling express might help: http://stackoverflow.com/a/30686457/4279201, but when I do that I get:
```
module.js:471
    throw err;
    ^


Error: Cannot find module './permuteDomain'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\viewer-steampunked-morgan-master\node_modules\request\node_modules\tough-cookie\lib\memstore.js:33:47)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

Any idea on how to get it to work?

PS: is there an updated repository where I can find a simple viewer like the old [2D3D viewer](https://github.com/Developer-Autodesk/viewer-navigation.sample) example?

**Comment by KeanW** [comment]
I took a look but couldn't reproduce the problem. If you're looking for a simpler integration sample, then I suggest posting to StackOverflow - someone on the Forge team will point you in the right direction.

**Comment by leefsmp** [comment]
Looks like an issue specific to your environment or your platform, that would be hard to diagnose on our side unfortunately. You can take a look at our other samples on [https://github.com/Autodesk-Forge](https://github.com/Autodesk-Forge). If you look for getting started code, I suggest you go through the step-by-step [tutorials](https://developer.autodesk.com/en/docs/viewer/v2/tutorials/) in the API documentation. You can then take any boiler plate and add the viewer to it. 

You may also take a look at my [boilers](https://github.com/Autodesk-Forge/forge-boilers.nodejs) sample, they go in increasing complexity from project #1 to #6
